aerial_autonomy_stacks.md
Hi, I have been following closely (but at the moment a bit quietly 😆 ) the ROS aerial robotics community working group, the work being done is amazing and I would like to contribute with this other interesting stack by **Multi-robot Systems Group UAV system** from the _Czech Technical University in Prague_.
Soon I will integrate more actively 😄
=> MRS UAV System stack

README.md, autopilots-suites.md
Just a list of available autopilots :)
=> Autopilot list add

README.md, simulation.md
Here a list of links of some common aerial robotics simulators. It's a nice start and at one point it might be nice to show an comparison, but as a start I think this is enough.
=> Create a list of simulators for aerial robotics

education_and_tutorial.md, hardware.md, middleware_and_drivers.md
Here are the changes that I think would benefit the project:
- Multiple typos were fixed
- mRo PixRacer Pro is indicated as an alternative to mRo PixRacer R15
- Control Zero H7 OEM added
- Parrot Mambo Driver added as a reference into middleware and drivers file
- Code Examples section created for education and tutorials.
- Mambo ROS Examples added to the Code Examples section
=> Corrections and additions into Hardware, Education and Tutorials, and Middleware and Drivers

message_standards.md
Started a page about message standards. 
It's just a start and it also needs a piece about RTPS, however I can't find any standards on those.
=> Add page about message standards

simulation.md
=> Simulation list update

hardware.md
Platforms added:
- 3DR Quad Zero Kit 
Flight Controllers added:
- 3DR Control Zero Classic
Extras:
Carrier boards for Control Zero H7 OEM and typos fixed
=> Update hardware.md, 3DR Products added

docs/aerial_autonomy_stacks.md
Reverts ROS-Aerial/aerial_robotic_landscape#44
=> Revert "Add ardupilot ros2 repo to indoor nav package list"

docs/aerial_autonomy_stacks.md
Renaming first entry in indoor navigation packages section
=> Rename Cartographer ROS to Ardupilot ROS

docs/aerial_autonomy_stacks.md, docs/aerial_vehicles.md, docs/autopilots_suites.md, docs/education_and_tutorial.md, docs/goatcounter.html, docs/hardware.md, docs/index.md, docs/message_standards.md, docs/middleware_and_drivers.md, docs/safety_management.md, docs/simulation.md, goatcounter.js, mkdocs.yml
Adding the goatcounter no-cookie viewer tracking to website
=> adding goatcounter to website

docs/index.md, docs/safety_management.md, mkdocs.yml
I added admonitions usage to this repo, the first instance is used to welcome new contributions.
Also, I fixed a typo for a link.
Please let me know if changes are required.
=> Admonitions enabled, Contibution message added, link typo fixed

docs/hardware.md
Refresh the reference hardware section
=> Update flight controllers, companion comp., cameras, dev kits

docs/hardware.md
Adding Flapper Nimble+ by Flapper Drones
Research platforms separated to Copters and Flapping Wings
=> Update hardware.md | Flapping wing UAVs

docs/education_and_tutorial.md
Course Link : 
https://www.edx.org/learn/autonomous-robotics/eth-zurich-autonomous-mobile-robots?utm_campaign=social-sharing-course-page&utm_medium=social&utm_source=email
=> Addition of ETHx: Autonomous Mobile Robots online course

docs/aerial_autonomy_stacks.md
Added the Duckiedrone pidrone_pkg to the the list of indoor navigation packages
=> Added Duckiedrone to indoor navigation packages

docs/hardware.md
Adding the swarm platform from Fly4Future
https://fly4future.com/robofly/
=> Update hardware with new platform

docs/education_and_tutorial.md
This adds the multi-robot summerschool of Prague university to the aerial robotic landscape.
We might just need to check the rest of the links too.
=> Add RAS summerschool to education and tutorials

docs/hardware.md
Julien Mellet shared this on linkedin: https://www.linkedin.com/posts/julienmellet_omniquad-open-source-omnidirectional-quadrotor-activity-7313858159159263232-rS0R
=> Add OmniQuad to hardware

.github/workflows/build.yml, .github/workflows/preview.yml, pixi.lock, pixi.toml
This PR adds a new feature for maintainers. Using CI, we build and deploy PR previews to GitHub Pages and then post a link to the pull request so everyone can test changes before they go live.
additionally:
* cleans up the build workflow
* expands pixi platforms to osx/linux
=> pr previews

docs/education_and_tutorial.md
* Removing coursera
* Adding dates to the course creation dates
* Putting newest highest
=> update education page

docs/software.md
We had a great PR by #95 but the intro didn't render properly (since we couldn't check the rendering of the doc)
Here is a fix to make it more structured.
=> Fix software page

.github/workflows/update-dates.yaml
=> ci: submit pr with token permissions

docs/middleware_and_drivers.md
=> Adds ros2 driver for tello

docs/simulation.md
Add UAV inertia tool here. 
We don't really have a tools section but it will be a nice fit for this page.
See https://github.com/knmcguire/best-of-robot-simulators/issues/51#issuecomment-3187986414
=> add uav inertia tool

docs/aerial_autonomy_stacks.md
Added a new entry for 'Dynamic Swarms Crazyflie' to the aerial autonomy stacks table.
=> Update aerial autonomy stacks with new entry
